name: office_bingo
description: A new Flutter project.
publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  go_router: 13.2.0

  # Firebase
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
